FROM maven:3.6.3-jdk-11

ARG remoteUser
ARG remoteToken
ARG remoteHost
ARG repoName
ARG inProjectPomLocation

RUN mkdir -p /usr/apps
COPY sources /usr/apps/
WORKDIR /usr/apps
RUN git -c credential.helper='!f() { echo "username=${remoteUser}"; echo "password=${remoteToken}"; };f' clone --depth 1 --no-tags https://${remoteHost}/${remoteUser}/${repoName}.git
RUN mvn -f ${repoName}/${inProjectPomLocation}/pom.xml clean install -U
EXPOSE 8080
#ENTRYPOINT ["java", "-jar", "kata-engine.jar"]
ENTRYPOINT ["java", "-jar", "SafeCodeExecution-1.0-SNAPSHOT.jar"]