FROM maven:3.6.3-jdk-11

ARG remoteUser=SlavinaKlisarska
ARG remoteToken=67defa3b78c225ab12b7d4733dc470e6c065d553
ARG remoteHost=github.com
ARG repoName=FinalProjectBookLords
ARG inProjectPomLocation=BookLords

RUN mkdir -p /usr/apps
COPY sources /usr/apps/
WORKDIR /usr/apps
RUN git -c credential.helper='!f() { echo "username=${remoteUser}"; echo "password=${remoteToken}"; };f' clone --depth 1 --no-tags https://${remoteHost}/${remoteUser}/${repoName}.git
ENV MAVEN_CONFIG /usr/apps/.m2
RUN mvn -f ${repoName}/${inProjectPomLocation}/pom.xml clean install -o
EXPOSE 8080
#ENTRYPOINT ["java", "-jar", "kata-engine.jar"]
ENTRYPOINT ["java", "-jar", "SafeCodeExecution-1.0-SNAPSHOT.jar"]